app:
  env: dev
  redis:
    server: localhost:6379
    database: 0
    password: 123456
    timeout: 2000

logging:
  config: classpath:log4j2-dev.xml

om.adc.domain: localhost:19014

admob:
  client_id: replace_with_your_googleapi.client_id
  client_secret: replace_with_your_googleapi.client_secret

spring:
  ## datasource
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false
      username: root
      password: 12345678



amazon:
  aws:
    access-key-id: AKIAWD3H37CHHOIT4P5B
    access-key-secret: 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
  s3:
    default-bucket: mises-storage
    region: us-east-2
    endpoint: https://.com/

http.proxy: